import { Inter } from 'next/font/google'
import { FC, ReactNode } from 'react';
import Header from './components/Header/Header.component';
import SideBar from './components/SideBar/SideBar.component';
import styles from './page.module.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: ReactNode 
}

const RootLayout: FC<LayoutProps> = ( {children }) => { 

  return (
    <html>
      <body style={{margin: 0}}>
          <main>
            <SideBar></SideBar>
            <Header></Header>
             <section className={inter.className} style={{}}>
              <div style={{marginLeft: '250px',  height: 'calc(100vh - 80px)',
}}>
              {children}
              </div>
            </section>      
          </main>
      </body>

    </html>
  );}


  export default RootLayout;